### ISSUE TITLE
Investigate if our use of popcnt suffers from a false data dependency

### ISSUE THREAD

**Issue by tibbe** [haskell-unordered-containers/unordered-containers#104]
https://stackoverflow.com/questions/25078285/replacing-a-32-bit-loop-count-variable-with-64-bit-introduces-crazy-performance

**Comment by fryguybob** [comment]
For what it is worth, in some of my research I wondered the same thing and modified GHC to prevent this false dependency by emitting an instruction to clear the output register before the `popcnt` instruction.  It did not affect performance in my case, but changes in the future could potentially change the story.

**Comment by fryguybob** [comment]
Relevant ticket:

https://ghc.haskell.org/trac/ghc/ticket/13725

**Comment by sjakobi** [comment]
I think that we probably won't do anything about this in this library.

According to https://stackoverflow.com/a/25089720/1013393, the issue has been fixed in recent Intel CPUs.

If anything needs to be done on the Haskell side, it would probably have to happen in GHC. This is tracked in https://gitlab.haskell.org/ghc/ghc/-/issues/13725.
