### ISSUE TITLE
Add isSubsetOf

### ISSUE THREAD

**Issue by rwbarton** [haskell-unordered-containers/unordered-containers#127]
`Data.Set` has a fuction `isSubsetOf :: Ord a => Set a -> Set a -> Bool`. I needed the corresponding function for `Data.HashSet`, and it should be possible to implement it more efficiently than can be done through the public interface of `Data.HashSet` currently.

**Comment by bjin** [comment]
I'm also interested in having a `isSubmapOf` function for `HashMap`, just like the one from `Map` and `IntMap`. I have a few ideas but not sure which one is the best way to implement it. @tibbe 

1. Implement `isSubmapOf` recursively over two `HashMap`, perform case-by-case analysis like current implementation of `unionWith`. This is complicated to implement and quite error-prone. I also have concern regarding commit https://github.com/tibbe/unordered-containers/commit/df6c50e1369d0ce76ff1b34776a0f5dc5edcc88c. What's the current status of the issue in this commit? Is `BitmapIndexed` guaranteed to have more than `1` and less than `full` children now?

2. Implement `isSubmapOf` like current implementation of `(==)`, transform two `HashMap` into two lists of `Leaf`s and `Collision`s with `toList'` (see https://github.com/tibbe/unordered-containers/commit/df6c50e1369d0ce76ff1b34776a0f5dc5edcc88c). The left is linear scanning and case analysis with only `Leaf` and `Collision`. The problem with this approach is that in order to run in strictly linear complexity, we need to change the bits in top layer from least-significant to most-significant, this way the keys in the list returned by `toList'` is sorted in ordinary `Word` order. This might hurt the performance if the range of `hash key` is not a full `Word`. But in exchange, we can also implement `intersect` and `difference` in linear time easily.

**Comment by kozross** [comment]
I would very much like a subset-testing function too.

**Comment by treeowl** [comment]
Yes, this seems like a good idea. Let's do it the fastest way. I've been wanting to add `mergeA` for a while; can we do that and use it for this? I don't remember if it has the right shape to do the job efficiently.

**Comment by sjakobi** [comment]
`isSubsetOf` was added in #282 and released v0.2.12.0.
