### ISSUE TITLE
When is ptrEq safe?

### ISSUE THREAD

**Issue by oberblastmeister** [haskell-unordered-containers/unordered-containers#408]
I see the function used many times, but I don't understand when it is safe to use.  There must be a reason why it is called 'reallyUnsafe'.

**Comment by treeowl** [comment]
`ptrEq` is just a wrapper around `reallyUnsafePtrEquality#`. The fundamental rule:

> If `ptrEq a b = True`, then `a` and `b` are the same. If `ptrEq a b = False`, then we have no idea whether `a` and `b` are the same or not.

The basic safety rule is that you should make sure code behaves (semantically) the same whether `ptrEq` returns `True` or `False`, under the accepted assumptions. We assume that if `a` and `b` are actually the same, then `a == b = True` and `forall s. hashWithSalt s a = hashWithSalt s b`. (`Eq` and `Hashable` instances that violate these assumptions get nasal demons.)

In addition to the safety rule, you should bear in mind that `reallyUnsafePtrEquality#` is much more likely to give a `True` result when its arguments have both been forced to WHNF. Otherwise, they'll be required to point to *the same thunk*.

**Comment by treeowl** [comment]
To summarize a bit more: it's not actually all that unsafe. It's just pointer equality. Oh yeah, I glossed over one point. There are special situations where a false result actually *does* mean something. In particular, I believe `False` should be reliable for enumeration types, because their values are tied to specific static memory locations. This can be used to implement "null pointers".

```haskell
data Null = Null  -- not exported

newtype Nullable a = Nullable a  -- exported abstractly

mkNull :: Nullable a
mkNull = unsafeCoerce Null

mkNonNull :: a -> Nullable a
mkNonNull = Nullable

deref :: Nullable a -> Maybe a
deref !(Nullable a)
  | ptrEq a (unsafeCoerce# Null)
  = Nothing
  | otherwise
  = Just a
```

This technique can actually be used to produce multiple null pointers. This stuff is all pretty nasty, but it might make sense if you want an array/vector of `Maybe`s and don't want to pay the indirection cost.

**Comment by sjakobi** [comment]
> In particular, I believe `False` should be reliable for enumeration types, because their values are tied to specific static memory locations. This can be used to implement "null pointers".

That sounds pretty useful. Are you aware of any existing code that uses this technique?

**Comment by treeowl** [comment]
I learned the technique (or variations thereof) from @ekmett, so probably. I think he was using slightly different null targets which won't work right anymore.

**Comment by treeowl** [comment]
@sjakobi, some of that probably isn't going to make it in there, because GHC HQ will be very reluctant to make any guarantees about it returning true. We're hacking around the edges a bit. It'd be really nice to get one or two official operations for dealing with nulls, which would do the same sorts of things but with guarantees.

**Comment by ekmett** [comment]
@oberblastmeister The issues with why `reallyUnsafePtrEquality#` is as 'really unsafe' as it is, is it can give perfectly reasonable false negatives in cases where SCCs are being updated, or when the value isn't forced, or where profiling is enabled, or whenever we ever get around to concurrent GC. The current code uses it opportunistically to avoid uselessly copying the path to the root of the structure and in the process avoids creating the usual intermediate structures you'd usually have to have to stick those results in 'Maybe's or the like on the way, even further reducing the garbage produced.
