### ISSUE TITLE
Use better char data for benchmarking

### ISSUE THREAD

**Issue by jmaessen** [haskell-unordered-containers/unordered-containers#8]
Lowercase alphabetic strings happen to not induce any hash collisions with the current choice of hash function.  Sprinkling in digits so that characters are chosen from ['0'..'9']++['a'..'z'] sends the collision rate through the roof, to something like 80%.  Really, any choice of >33 characters seems to work reasonably well; you can for example try mixed upper and lower case.  Using more interesting string data would permit realistic benchmarking (and would encourage the use of a less problematic hash function, I bet).

**Comment by sjakobi** [comment]
Back when this issue was opened, `hashable`'s string hashing algorithm was "Bernstein". These days, `hashable` is using "FNV", so it's not clear that the benchmarking changes suggested would still be helpful.

Feel free to reopen the issue (or better make a new one) if there's evidence that the suggested changes would still be useful.
